<?php
/**
 * Created by PhpStorm.
 * User: xiaohao
 * Date: 17-11-23
 * Time: 上午11:03
 */

namespace App\Http\Controllers;


use Illuminate\Http\Request;

class RequestController extends Controller
{

    public function req(Request $request)
    {
        //可以通过request的方法判断request的方法
        //  dd($request->method());


        // dd($request->url());
       //  dd($request->id);



        return; // TODO: Change the autogenerated stub
    }

    public function add(Request $request)
    {
        dd($request->input("username"));
    }
}