<?php
/**
 * Created by PhpStorm.
 * User: xiaohao
 * Date: 17-11-23
 * Time: 下午2:30
 */

namespace App\Http\Controllers;
class ViewController extends Controller
{

    public function show()
    {
        $name = "xiaohao";
        return view("layout.view", ["name" => $name]);

    }

    public function template()
    {
        return view("template.child"); // TODO: Change the autogenerated stub
    }

    public function blade()
    {
        return view("layout.display", ["name" => "老王"]);
    }
}


?>